name: Update Reflecting Last Week Gist

on:
  schedule:
    # 매일 한국 시간 기준 오전 0시 10분에 실행 (UTC 15:10)
    - cron: '10 15 * * *'
  workflow_dispatch: # 수동으로도 실행할 수 있게 버튼 활성화

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/checkout@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install PyGithub python-dotenv

      - name: Run analysis
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: python main.py